### PR TITLE
Add Simple Scene with Camera Movement

### PR DESCRIPTION
**Pull request by PatrickAdelberger**
# Summary
Added the simple scene to the camer movement implementation from Jonathan. Also checked his implentation it seems fine and worked for me. But please have a look again.
CG_simple_scene

## Additional Help for the Students
With the inclusion of this simple scene students get a example on how to use:
- a scenegraph
- different shaders
- different SGNodes from the framework: in the tutorial they are mostly reimplemented in the main.js file and are named differently.
- a light source
- camera movement

## Grading (edit)
Check if the project specifications are still OK:
1. **(13)** Composed object
  1.1. **(6)** Manually composed object :heavy_check_mark: 
  1.2. **(4)** Animate seperate parts :heavy_check_mark: 
  1.3. **(3)** Two different materials: The scene uses MaterialSGNode, but there is not much difference to the tutorial examples :heavy_check_mark: 
2. **(10)** Complex object
  2.1. **(7)** 3D object :heavy_check_mark: 
  2.2. **(3)** Texture for the object :heavy_check_mark: 
3. **(18)** Illumination
  3.1. **(5)** Use mutliple light sources: The scene has one light source (optional we could specify more than 3 light sources) :question: 
  3.2. **(3)** One light source should be moving: (~~The light source moves in the scene, but according to 3.1 additional light sources have to be added. The movement itself is rather simple, too. :question:~~) :heavy_check_mark: 
  3.3. **(7)** Spot-light :heavy_check_mark: 
  3.4. **(3)** Apply Phong shading to all object: The scene uses Phong shading on all objects, but the scene itself is simple and is also in the tutorials available. The students have to use textures with the shading, which seems still complicated enough. :question:  
4. **(9)** Camera
  4.1. **(6)** WASD movement: Is now part of the framework :x: 
  4.2. **(3)** Mouse control: Is now part of the framework :x:
5. **(10)** Animations
  5.1. **(2)** Automatic start :heavy_check_mark: 
  5.2. **(3)** Framerate-independent: The scene uses the timeInMilliseconds variable, but ther is no mentioning that it is linkt to that :question: 
  5.3. **(5)** Camer animation :heavy_check_mark: 

### Changes
I think only the **4.Camera** specification has to be removed. The possible changes are not relevant, because that are just simple code parts from the tutorial used together in one scene, in my opinon. 

### Point Distribution Change 
We have to update the point distribution, due to the now obsolete camer part, which were 9 points. 
I would add most of the points to the **2. Complex object** and **3. Illumination** sections, because that were the ones that the students skipt or only partially implemented.
**Suggestion**: (edit)
1.3. Two material for the composed object: +1 -> **4**

2.1. Create complex object with all properties: (~~+1 -> **8**~~) +2 -> 9
2.2. Texture for the complex object: +3 -> **6**

3.1. use mulitple light source: (~~+1 -> **6**~~) +0 -> 5
3.3. Spot-light: +2 -> **9**
3.4. Apply Phong shading: +1 -> **4**

:warning:  **Attention**: 
 - adapted the _Effects_ section of the README in this repository
 - check specifications in Moodle

### CODE REVIEW

**Comment by keckelt** [comment]
Can you add basic camera instructions to the README, i.e.,  WASD + mouse?

**Comment by keckelt** [comment]
We could also use the simple lightning instead of phong, right?

I mean, the effort to do it was quite low anyway so its fine with included üpphong shading too. Also  it might be easier for the students to get started with the real work if phong shader is already in place.

**Comment by PatrickAdelberger** [comment]
> Can you add basic camera instructions to the README, i.e., WASD + mouse?

@keckelt I added the camera instruction. Please take a look if they are sufficient and if its postion in the README is OK

**Comment by keckelt** [comment]
> 2.1. Create complex object with all properties: +1 -> 8

I think we can also give 9 points for that and one points less for phong shading or multiple light sources.


the movement of the light source in this scene can be removed imo

**Comment by PatrickAdelberger** [comment]
> > 2.1. Create complex object with all properties: +1 -> 8
> 
> I think we can also give 9 points for that and one points less for phong shading or multiple light sources.

I think giving 2.1 Create complex object an extra point is fine, I would remove it from the '3.1 use mulitple light sources'.

> the movement of the light source in this scene can be removed imo

Okay

**Comment by PatrickAdelberger** [comment]
@keckelt 
I updated the point distribution in the README and the PR description and removed the movement of the light in the scene.
GIF
cg_lab_simple_scene

**Comment by mstreit** [comment]
I think it's sufficient to document the camera movement on the Moodle page. The README should ONLY contain information that students need to provide to us. Everything else just clutters the README.

**Comment by PatrickAdelberger** [comment]
> I think it's sufficient to document the camera movement on the Moodle page. The README should ONLY contain information that students need to provide to us. Everything else just clutters the README.

Removed the camera movement instructions form the README

**Review by keckelt — APPROVED** [review]
ok

**Pull request merged**
